# GNU Make project makefile autogenerated by Premake

ifndef config
  config=release_linux64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),release_linux64)
  RESCOMP = windres
  TARGETDIR = ../..
  TARGET = $(TARGETDIR)/pytiledb.so
  OBJDIR = obj
  DEFINES += -DHAVE_PYCONFIG -DNDEBUG
  INCLUDES += -I../src/tiledb/cxx_api -I../src/tiledb_pybind -I. -Iinclude -I../include -I/opt/boost_1_68_0 -I/usr/include -I/usr/local/include -I/opt/anaconda3/include -I/opt/anaconda3/include/python3.7m -I/opt/anaconda3/lib/python3.7/site-packages/pyarrow/include -I../../../pybind11-2.6.1/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -m64 -std=gnu++0x -fPIC -D_GLIBCXX_USE_NANOSLEEP -D_THREAD_SAFE -D_XOPEN_SOURCE_EXTENEDED -D_GCC -D_PROTOTYPES -D_DRTP_V4 -DLINUX -D_POSIX_THREADS
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -m64 -std=gnu++0x -fPIC -D_GLIBCXX_USE_NANOSLEEP -D_THREAD_SAFE -D_XOPEN_SOURCE_EXTENEDED -D_GCC -D_PROTOTYPES -D_DRTP_V4 -DLINUX -D_POSIX_THREADS
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L. -L/usr/lib64 -L/usr/local/lib -L/usr/local/lib64 -L/opt/anaconda3/lib -L/opt/anaconda3/lib/python3.7/site-packages/pyarrow -L/usr/lib64 -m64 -shared -Wl,-soname=pytiledb.so -s -m64 -std=gnu++0x -fPIC -D_GLIBCXX_USE_NANOSLEEP -D_THREAD_SAFE -D_XOPEN_SOURCE_EXTENEDED -D_GCC -D_PROTOTYPES -D_DRTP_V4 -DLINUX -D_POSIX_THREADS -lm -lrt -lpthread -lstdc++ -ldl -lpython3.7m -l :libarrow.so.200 -l :libarrow_python.so.200 -l :libtiledb.so.2.0
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/tiledb_cxx_array_util.o \
	$(OBJDIR)/tiledb_cxx_column.o \
	$(OBJDIR)/tiledb_cxx_string_util.o \
	$(OBJDIR)/init_module_common.o \
	$(OBJDIR)/init_module_pybind.o \
	$(OBJDIR)/pybind_tiledb_cxx.o \
	$(OBJDIR)/pybind_tiledb_cxx_array.o \
	$(OBJDIR)/pybind_tiledb_cxx_array_schema.o \
	$(OBJDIR)/pybind_tiledb_cxx_array_util.o \
	$(OBJDIR)/pybind_tiledb_cxx_attribute.o \
	$(OBJDIR)/pybind_tiledb_cxx_column.o \
	$(OBJDIR)/pybind_tiledb_cxx_config.o \
	$(OBJDIR)/pybind_tiledb_cxx_context.o \
	$(OBJDIR)/pybind_tiledb_cxx_core_interface.o \
	$(OBJDIR)/pybind_tiledb_cxx_dimension.o \
	$(OBJDIR)/pybind_tiledb_cxx_domain.o \
	$(OBJDIR)/pybind_tiledb_cxx_exception.o \
	$(OBJDIR)/pybind_tiledb_cxx_filter.o \
	$(OBJDIR)/pybind_tiledb_cxx_filter_list.o \
	$(OBJDIR)/pybind_tiledb_cxx_group.o \
	$(OBJDIR)/pybind_tiledb_cxx_object.o \
	$(OBJDIR)/pybind_tiledb_cxx_object_iter.o \
	$(OBJDIR)/pybind_tiledb_cxx_query.o \
	$(OBJDIR)/pybind_tiledb_cxx_stats.o \
	$(OBJDIR)/pybind_tiledb_cxx_string_util.o \
	$(OBJDIR)/pybind_tiledb_cxx_type.o \
	$(OBJDIR)/pybind_tiledb_cxx_utils.o \
	$(OBJDIR)/pybind_tiledb_cxx_version.o \
	$(OBJDIR)/pybind_tiledb_cxx_vfs.o \
	$(OBJDIR)/pybind_tiledb_enum.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking pytiledb
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning pytiledb
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/tiledb_cxx_array_util.o: ../src/tiledb/cxx_api/tiledb_cxx_array_util.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tiledb_cxx_column.o: ../src/tiledb/cxx_api/tiledb_cxx_column.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tiledb_cxx_string_util.o: ../src/tiledb/cxx_api/tiledb_cxx_string_util.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/init_module_common.o: ../src/tiledb_pybind/init_module_common.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/init_module_pybind.o: ../src/tiledb_pybind/init_module_pybind.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx.o: ../src/tiledb_pybind/pybind_tiledb_cxx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_array.o: ../src/tiledb_pybind/pybind_tiledb_cxx_array.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_array_schema.o: ../src/tiledb_pybind/pybind_tiledb_cxx_array_schema.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_array_util.o: ../src/tiledb_pybind/pybind_tiledb_cxx_array_util.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_attribute.o: ../src/tiledb_pybind/pybind_tiledb_cxx_attribute.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_column.o: ../src/tiledb_pybind/pybind_tiledb_cxx_column.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_config.o: ../src/tiledb_pybind/pybind_tiledb_cxx_config.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_context.o: ../src/tiledb_pybind/pybind_tiledb_cxx_context.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_core_interface.o: ../src/tiledb_pybind/pybind_tiledb_cxx_core_interface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_dimension.o: ../src/tiledb_pybind/pybind_tiledb_cxx_dimension.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_domain.o: ../src/tiledb_pybind/pybind_tiledb_cxx_domain.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_exception.o: ../src/tiledb_pybind/pybind_tiledb_cxx_exception.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_filter.o: ../src/tiledb_pybind/pybind_tiledb_cxx_filter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_filter_list.o: ../src/tiledb_pybind/pybind_tiledb_cxx_filter_list.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_group.o: ../src/tiledb_pybind/pybind_tiledb_cxx_group.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_object.o: ../src/tiledb_pybind/pybind_tiledb_cxx_object.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_object_iter.o: ../src/tiledb_pybind/pybind_tiledb_cxx_object_iter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_query.o: ../src/tiledb_pybind/pybind_tiledb_cxx_query.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_stats.o: ../src/tiledb_pybind/pybind_tiledb_cxx_stats.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_string_util.o: ../src/tiledb_pybind/pybind_tiledb_cxx_string_util.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_type.o: ../src/tiledb_pybind/pybind_tiledb_cxx_type.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_utils.o: ../src/tiledb_pybind/pybind_tiledb_cxx_utils.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_version.o: ../src/tiledb_pybind/pybind_tiledb_cxx_version.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_cxx_vfs.o: ../src/tiledb_pybind/pybind_tiledb_cxx_vfs.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pybind_tiledb_enum.o: ../src/tiledb_pybind/pybind_tiledb_enum.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif